"""The Siemens OZW672 integration."""

from __future__ import annotations

import logging
from typing import Any

import voluptuous as vol

from homeassistant.config_entries import ConfigEntry
from homeassistant.const import Platform
from homeassistant.core import HomeAssistant, ServiceCall
from homeassistant.helpers import config_validation as cv
from homeassistant.helpers.aiohttp_client import async_get_clientsession
from homeassistant.helpers.typing import ConfigType

from .api import OZW672Client
from .const import (
    ATTR_DATAPOINT_ID,
    ATTR_VALUE,
    ATTR_VALUE_TYPE,
    CONF_CUSTOM_DATAPOINTS,
    CONF_DATAPOINTS,
    CONF_DISABLED_DATAPOINTS,
    CONF_HOST,
    CONF_PASSWORD,
    CONF_PORT,
    CONF_USE_HTTPS,
    CONF_USERNAME,
    CONF_VERIFY_SSL,
    DOMAIN,
    DP_ADDRESS,
    DP_DEVICE_CLASS,
    DP_ID,
    DP_MAX_VALUE,
    DP_MIN_VALUE,
    DP_NAME,
    DP_OPTIONS,
    DP_PATH,
    DP_PLATFORM,
    DP_STATE_CLASS,
    DP_STEP,
    DP_SUBKEY,
    DP_UNIT,
    DP_VALUE_TYPE,
    DP_WRITE_ACCESS,
    PLATFORM_SENSOR,
    SERVICE_WRITE_DATAPOINT,
    TYPE_ENUMERATION,
    TYPE_NUMERIC,
)
from .coordinator import SiemensOZW672Coordinator

_LOGGER = logging.getLogger(__name__)

PLATFORMS: list[Platform] = [
    Platform.SENSOR,
    Platform.NUMBER,
    Platform.SELECT,
    Platform.BINARY_SENSOR,
]

CONFIG_SCHEMA = cv.config_entry_only_config_schema(DOMAIN)


def _get_coordinator(entry: ConfigEntry) -> SiemensOZW672Coordinator | None:
    """Return the coordinator of an entry, if it is loaded."""
    coordinator = getattr(entry, "runtime_data", None)
    return coordinator if isinstance(coordinator, SiemensOZW672Coordinator) else None


async def async_setup(hass: HomeAssistant, config: ConfigType) -> bool:
    """Register the integration services."""

    async def _async_write_datapoint(call: ServiceCall) -> None:
        """Write an arbitrary datapoint value."""
        entry_id: str | None = call.data.get("entry_id")
        coordinators: list[SiemensOZW672Coordinator] = []

        if entry_id:
            entry = hass.config_entries.async_get_entry(entry_id)
            coordinator = _get_coordinator(entry) if entry else None
            if coordinator is not None:
                coordinators.append(coordinator)
        else:
            for entry in hass.config_entries.async_entries(DOMAIN):
                coordinator = _get_coordinator(entry)
                if coordinator is not None:
                    coordinators.append(coordinator)

        if not coordinators:
            raise ValueError("No loaded Siemens OZW672 config entry found")

        for coordinator in coordinators:
            await coordinator.client.async_write_datapoint(
                int(call.data[ATTR_DATAPOINT_ID]),
                call.data[ATTR_VALUE],
                call.data.get(ATTR_VALUE_TYPE, TYPE_NUMERIC),
            )
            await coordinator.async_request_refresh()

    hass.services.async_register(
        DOMAIN,
        SERVICE_WRITE_DATAPOINT,
        _async_write_datapoint,
        schema=vol.Schema(
            {
                vol.Optional("entry_id"): cv.string,
                vol.Required(ATTR_DATAPOINT_ID): vol.All(
                    vol.Coerce(int), vol.Range(min=1)
                ),
                vol.Required(ATTR_VALUE): vol.Any(str, int, float),
                vol.Optional(ATTR_VALUE_TYPE, default=TYPE_NUMERIC): vol.In(
                    [TYPE_NUMERIC, TYPE_ENUMERATION]
                ),
            }
        ),
    )

    return True


async def async_migrate_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool:
    """Migrate a version 1 entry to version 2.

    Version 1 identified the datapoints by their numeric identifier and shipped
    a built-in catalog. The identifiers are generated by the OZW672 for the
    plant it is wired to, so version 2 identifies them by their topic path and
    stores the identifier only as a cache. The built-in catalog of version 1
    cannot be migrated (it only ever matched the reference installation): the
    datapoints that were declared manually are kept, the others have to be
    selected again in the options.
    """
    if entry.version > 2:
        _LOGGER.error(
            "Cannot downgrade the Siemens OZW672 entry %s from version %s",
            entry.entry_id,
            entry.version,
        )
        return False

    if entry.version == 1:
        options = dict(entry.options)
        datapoints: dict[str, Any] = {}
        custom = options.get(CONF_CUSTOM_DATAPOINTS) or {}
        for raw_id, config in custom.items():
            try:
                datapoint_id = int(raw_id)
            except (TypeError, ValueError):
                continue
            config = config if isinstance(config, dict) else {}
            key = f"id:{datapoint_id}"
            datapoints[key] = {
                DP_ID: datapoint_id,
                DP_NAME: config.get("name") or f"Datapoint {datapoint_id}",
                DP_PATH: None,
                DP_ADDRESS: None,
                DP_SUBKEY: None,
                DP_WRITE_ACCESS: False,
                DP_PLATFORM: config.get("platform") or PLATFORM_SENSOR,
                DP_VALUE_TYPE: config.get("value_type") or TYPE_NUMERIC,
                DP_UNIT: config.get("unit") or None,
                DP_DEVICE_CLASS: config.get("device_class") or None,
                DP_STATE_CLASS: config.get("state_class") or None,
                DP_OPTIONS: config.get("options") or None,
                DP_MIN_VALUE: config.get("min_value"),
                DP_MAX_VALUE: config.get("max_value"),
                DP_STEP: config.get("step"),
            }

        options[CONF_DATAPOINTS] = datapoints
        options.pop(CONF_CUSTOM_DATAPOINTS, None)
        options.pop(CONF_DISABLED_DATAPOINTS, None)
        hass.config_entries.async_update_entry(entry, options=options, version=2)
        _LOGGER.info(
            "Migrated the Siemens OZW672 entry %s to version 2 (%s manually "
            "declared datapoints kept). The built-in datapoint catalog has been "
            "removed: select the datapoints of your installation again in the "
            "integration options.",
            entry.entry_id,
            len(datapoints),
        )

    return True


async def async_setup_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool:
    """Set up a Siemens OZW672 config entry."""
    session = async_get_clientsession(hass)
    client = OZW672Client(
        session,
        entry.data[CONF_HOST],
        entry.data[CONF_USERNAME],
        entry.data[CONF_PASSWORD],
        port=entry.data.get(CONF_PORT),
        use_https=entry.data.get(CONF_USE_HTTPS, False),
        verify_ssl=entry.data.get(CONF_VERIFY_SSL, False),
    )

    coordinator = SiemensOZW672Coordinator(hass, entry, client)
    await coordinator.async_resolve_identifiers()
    await coordinator.async_config_entry_first_refresh()

    entry.runtime_data = coordinator
    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
    entry.async_on_unload(entry.add_update_listener(_async_update_listener))

    return True


async def async_unload_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool:
    """Unload a Siemens OZW672 config entry."""
    unload_ok = await hass.config_entries.async_unload_platforms(entry, PLATFORMS)
    if unload_ok:
        coordinator = _get_coordinator(entry)
        if coordinator is not None:
            await coordinator.client.async_logout()
    return unload_ok


async def _async_update_listener(hass: HomeAssistant, entry: ConfigEntry) -> None:
    """Reload the entry when its options change."""
    await hass.config_entries.async_reload(entry.entry_id)
