"""Async client for the Siemens OZW672 (web server) HTTP API.

The OZW672 exposes a small JSON API on top of its web interface:

* ``GET /api/auth/login.json?user=<user>&pwd=<password>`` returns the session.
* ``GET /api/menutree/list.json?SessionId=<sid>&Id=<node>`` returns the
  sub-topics (``MenuItems``) and the datapoints (``DatapointItems``) of a
  node of the menu tree.
* ``GET /api/menutree/read_datapoint.json?SessionId=<sid>&Id=<datapoint>``
  returns ``{"Data": {"Type": ..., "Value": ..., "Unit": ...}}``.
* ``GET /api/menutree/write_datapoint.json?SessionId=<sid>&Id=<datapoint>``
  with the extra ``Type=<type>&Value=<value>`` parameters writes a datapoint.

The identifiers of the datapoints are generated by the OZW672 for the plant it
is wired to: they are different for every installation and can even change on
a given installation when the plant or the server parameters are refreshed.
The menu tree is therefore the reference: a datapoint is identified by its
topic path and the identifier is resolved again at every setup.
"""

from __future__ import annotations

import asyncio
import json
import logging
from collections.abc import Iterable
from typing import Any

import aiohttp

from .const import (
    DP_ADDRESS,
    DP_ID,
    DP_NAME,
    DP_PATH,
    DP_SUBKEY,
    DP_WRITE_ACCESS,
    INVALID_TOKENS,
    TYPE_NUMERIC,
)

_LOGGER = logging.getLogger(__name__)

REQUEST_TIMEOUT = 15

_READ_DATAPOINT = "/api/menutree/read_datapoint.json"
_WRITE_DATAPOINT = "/api/menutree/write_datapoint.json"
_LIST_MENUTREE = "/api/menutree/list.json"
_DATAPOINT_DESC = "/api/menutree/datapoint_desc.json"
_DEVICE_INFO = "/api/device/info.json"
_LOGIN = "/api/auth/login.json"
_LOGOUT = "/api/auth/logout.json"

_TRUE_TOKENS = frozenset({"true", "1", "yes", "on"})


class OZW672Error(Exception):
    """Base class for OZW672 errors."""


class OZW672ConnectionError(OZW672Error):
    """Raised when the OZW672 cannot be reached."""


class OZW672AuthError(OZW672Error):
    """Raised when authentication with the OZW672 fails."""


class OZW672ApiError(OZW672Error):
    """Raised when the OZW672 API returns an unexpected response."""


def _extract_error(payload: Any) -> str | None:
    """Return the device side error message of a response, if there is one.

    Failures are reported by the OZW as, for example::

        {"Data": {},
         "Result": {"Success": "false",
                    "Error": {"Txt": "read failed", "Nr": "6"}}}
    """
    if not isinstance(payload, dict):
        return None

    for value in (payload, payload.get("Data"), payload.get("Result")):
        if not isinstance(value, dict):
            continue

        error = value.get("Error", value.get("error"))
        if isinstance(error, dict):
            text = error.get("Txt", error.get("Text", error.get("txt")))
            number = error.get("Nr", error.get("nr"))
            if text:
                return f"{text} (Nr {number})" if number is not None else str(text)
            return json.dumps(error, sort_keys=True)
        if isinstance(error, str) and error:
            return error

        success = value.get("Success", value.get("success"))
        if success is not None and str(success).lower() in {"false", "0", "no"}:
            return "unknown device error"

    return None


def _normalise_value(value: Any) -> Any:
    """Clean up a raw datapoint value.

    The OZW672 right-pads numeric values with spaces and reports datapoints
    that are configured but not wired on the plant with a dash pattern.
    """
    if not isinstance(value, str):
        return value
    text = value.strip()
    if not text or text in INVALID_TOKENS:
        return None
    return text


def _to_int(value: Any) -> int | None:
    """Convert a device value into an integer when possible."""
    if value is None or isinstance(value, bool):
        return None
    try:
        return int(str(value).strip())
    except (TypeError, ValueError):
        return None


def _to_float(value: Any) -> float | None:
    """Convert a device value into a float when possible."""
    if value is None or isinstance(value, bool):
        return None
    try:
        return float(str(value).strip())
    except (TypeError, ValueError):
        return None


def _parse_description(description: dict[str, Any]) -> dict[str, Any]:
    """Normalise a ``datapoint_desc`` response.

    The description is what tells how a datapoint must be exposed: its type,
    its unit, the allowed range and, for an enumeration or a radio button, the
    values the controller accepts with their labels.
    """
    options: dict[str, str] = {}
    enums = description.get("Enums")
    if isinstance(enums, list):
        for entry in enums:
            if not isinstance(entry, dict):
                continue
            code = _normalise_value(entry.get("Value"))
            if code is None:
                continue
            label = _normalise_value(entry.get("Text"))
            options[str(code)] = str(label) if label is not None else str(code)

    buttons = description.get("Buttons")
    if not options and isinstance(buttons, list):
        for entry in buttons:
            if not isinstance(entry, dict):
                continue
            for code, key in ((0, "TextOpt0"), (1, "TextOpt1")):
                label = _normalise_value(entry.get(key))
                if label is not None:
                    options.setdefault(str(code), str(label))

    unit = _normalise_value(description.get("Unit"))
    hours = description.get("Hours")
    if isinstance(hours, dict):
        unit = unit or "h"
        minimum = _to_float(hours.get("Min"))
        maximum = _to_float(hours.get("Max"))
        resolution = _to_float(hours.get("Resolution"))
    else:
        minimum = _to_float(description.get("Min"))
        maximum = _to_float(description.get("Max"))
        resolution = _to_float(description.get("Resolution"))

    valid = _normalise_value(description.get("IsValid"))

    return {
        "type": _normalise_value(description.get("Type")),
        "name": _normalise_value(description.get("Name")),
        "unit": unit,
        "min": minimum,
        "max": maximum,
        "resolution": resolution,
        "options": options,
        "valid": None if valid is None else str(valid).strip().lower() in _TRUE_TOKENS,
    }


def _item_title(item: dict[str, Any]) -> str:
    """Return the human readable title of a menutree item."""
    text = item.get("Text")
    if isinstance(text, dict):
        title = text.get("Long") or text.get("Short")
        if title:
            return str(title).strip()
    return ""


def _unique_title(item: dict[str, Any], counters: dict[str, int]) -> str:
    """Return a title that is unique among the siblings of a menutree node.

    Titles repeated by the controller are suffixed with ``#2``, ``#3`` ... so
    that the generated topic paths stay unique and reproducible.
    """
    base = _item_title(item) or f"#{_to_int(item.get('Id'))}"
    counters[base] = counters.get(base, 0) + 1
    count = counters[base]
    return base if count == 1 else f"{base} #{count}"


def _is_prefix(candidate: tuple[str, ...], wanted: set[tuple[str, ...]]) -> bool:
    """Return True when ``candidate`` is a prefix of one of the wanted paths."""
    return any(
        len(candidate) <= len(target) and target[: len(candidate)] == candidate
        for target in wanted
    )


class OZW672Client:
    """Thin async wrapper around the OZW672 web API."""

    def __init__(
        self,
        session: aiohttp.ClientSession,
        host: str,
        username: str,
        password: str,
        *,
        port: int | None = None,
        use_https: bool = False,
        verify_ssl: bool = False,
    ) -> None:
        """Initialise the client."""
        self._session = session
        self._username = username
        self._password = password
        self._verify_ssl = verify_ssl
        self._session_id: str | None = None
        self._lock = asyncio.Lock()
        self._warned_payloads: set[int] = set()

        scheme = "https" if use_https else "http"
        authority = host
        if port:
            # ``port`` may be a float coming from a Home Assistant number
            # selector (``80.0``) and would otherwise produce an invalid URL.
            authority = f"{host}:{int(float(port))}"
        self.base_url = f"{scheme}://{authority}"

    @property
    def session_id(self) -> str | None:
        """Return the current session id, if any."""
        return self._session_id

    async def async_login(self) -> None:
        """Force a new login."""
        async with self._lock:
            await self._async_login()

    async def async_ensure_session(self) -> str:
        """Login if no session id is available yet."""
        async with self._lock:
            if self._session_id is None:
                await self._async_login()
            assert self._session_id is not None
            return self._session_id

    async def async_logout(self) -> None:
        """Log out and forget the current session id."""
        async with self._lock:
            if self._session_id is None:
                return
            try:
                await self._async_request(_LOGOUT, {"SessionId": self._session_id})
            except OZW672Error as err:
                _LOGGER.debug("Logout failed (ignored): %s", err)
            finally:
                self._session_id = None

    async def async_read_datapoint(self, datapoint_id: int) -> Any:
        """Read a single datapoint value."""
        return self._extract_value(datapoint_id, await self._async_read(datapoint_id))

    async def async_read_datapoint_details(self, datapoint_id: int) -> dict[str, Any]:
        """Read a datapoint and return its type, unit and current value."""
        payload = await self._async_read(datapoint_id)
        data = (
            payload.get("Data", payload.get("data"))
            if isinstance(payload, dict)
            else None
        )
        if not isinstance(data, dict):
            return {"value": self._extract_value(datapoint_id, payload)}
        return {
            "type": _normalise_value(data.get("Type")),
            "unit": _normalise_value(data.get("Unit")),
            "value": _normalise_value(data.get("Value")),
            "enum_value": _normalise_value(
                data.get("EnumValue", data.get("Enumvalue"))
            ),
        }

    async def async_read_datapoint_description(
        self, datapoint_id: int
    ) -> dict[str, Any]:
        """Read the description of a datapoint.

        Returns the type, the unit, the allowed range and, when the datapoint
        is an enumeration or a radio button, the values the controller accepts
        with the labels it uses, so the caller can decide whether the datapoint
        becomes a read only sensor or an entity that can be changed from Home
        Assistant.
        """
        session_id = await self.async_ensure_session()
        params: dict[str, Any] = {"SessionId": session_id, "Id": int(datapoint_id)}
        try:
            payload = await self._async_request(_DATAPOINT_DESC, params)
        except OZW672AuthError:
            _LOGGER.debug("Session expired, re-authenticating")
            await self.async_login()
            params["SessionId"] = self._session_id
            payload = await self._async_request(_DATAPOINT_DESC, params)

        error = _extract_error(payload)
        if error is not None:
            raise OZW672ApiError(
                f"Description of datapoint {datapoint_id} failed: {error}"
            )

        description = payload.get("Description") if isinstance(payload, dict) else None
        if not isinstance(description, dict):
            raise OZW672ApiError(
                f"Description of datapoint {datapoint_id} is missing from the response"
            )
        return _parse_description(description)

    async def _async_read(self, datapoint_id: int) -> Any:
        """Read a datapoint and return the raw payload (handles re-login)."""
        session_id = await self.async_ensure_session()
        params: dict[str, Any] = {"SessionId": session_id, "Id": int(datapoint_id)}
        try:
            payload = await self._async_request(_READ_DATAPOINT, params)
        except OZW672AuthError:
            _LOGGER.debug("Session expired, re-authenticating")
            await self.async_login()
            params["SessionId"] = self._session_id
            payload = await self._async_request(_READ_DATAPOINT, params)

        error = _extract_error(payload)
        if error is not None:
            raise OZW672ApiError(f"Read of datapoint {datapoint_id} failed: {error}")
        return payload

    def _extract_value(self, datapoint_id: int, payload: Any) -> Any:
        """Pull the value out of a ``read_datapoint`` response.

        The documented shape is ``{"Data": {"Value": <value>}}`` but the
        firmware is not consistent about the capitalisation and about where the
        value lives, so several shapes are accepted. An unrecognised payload is
        reported once per datapoint instead of silently yielding ``None``.
        """
        _LOGGER.debug("Datapoint %s raw response: %r", datapoint_id, payload)

        if isinstance(payload, dict):
            for key in ("Value", "value"):
                if key in payload:
                    return _normalise_value(payload[key])

            data = payload.get("Data", payload.get("data"))
            if isinstance(data, dict):
                for key in ("Value", "value"):
                    if key in data:
                        return _normalise_value(data[key])
            elif isinstance(data, (int, float, str, bool)):
                return _normalise_value(data)
        elif isinstance(payload, (int, float, str, bool)):
            return _normalise_value(payload)

        if datapoint_id not in self._warned_payloads:
            self._warned_payloads.add(datapoint_id)
            _LOGGER.warning(
                "Unexpected response for datapoint %s: %r. Please report this "
                "payload at https://github.com/Didier57/Siemens-OZW672.01/issues",
                datapoint_id,
                payload,
            )
        return None

    async def async_list_devices(self) -> list[dict[str, Any]]:
        """Return the devices known by the OZW672.

        Datapoint identifiers are generated for the plant the OZW672 is wired
        to, so the devices of a plant are the entries of the menutree root
        node: every controller on the bus shows up there with its bus address
        and its type (for example ``1 RVS21.831F/127``).
        """
        payload = await self._async_session_request(_LIST_MENUTREE, {"Id": ""})
        items = payload.get("MenuItems") if isinstance(payload, dict) else None
        if not isinstance(items, list):
            error = _extract_error(payload)
            if error is not None:
                raise OZW672ApiError(f"Cannot list the OZW672 devices: {error}")
            return []

        devices: list[dict[str, Any]] = []
        for item in items:
            if not isinstance(item, dict):
                continue
            device_id = _to_int(item.get("Id"))
            if device_id is None:
                continue
            name = _item_title(item) or f"Device {device_id}"
            devices.append({"id": device_id, "name": name})
        return devices

    async def async_get_device_info(self) -> dict[str, Any]:
        """Return the gateway information (name, serial number, firmware)."""
        payload = await self._async_session_request(_DEVICE_INFO, {})
        if isinstance(payload, dict) and isinstance(payload.get("Device"), dict):
            return dict(payload["Device"])
        return {}

    async def async_walk_datapoints(
        self,
        root_id: int | None = None,
        wanted_paths: Iterable[str] | None = None,
    ) -> list[dict[str, Any]]:
        """Walk the menu tree and describe every datapoint it contains.

        When ``wanted_paths`` is given the walk only descends into the branches
        that lead to one of those paths, which keeps the resolution of an
        already configured entry cheap. Without it the whole tree below
        ``root_id`` is enumerated, which is what the configuration flow needs
        in order to offer the topics to the user.

        Sibling nodes sharing a title are suffixed with ``#2``, ``#3`` ... so
        that the returned paths are unique and stable.
        """
        wanted: set[tuple[str, ...]] | None = None
        if wanted_paths is not None:
            wanted = set()
            for raw in wanted_paths:
                parts = tuple(
                    part.strip() for part in str(raw).split("/") if part.strip()
                )
                if parts:
                    wanted.add(parts)

        results: list[dict[str, Any]] = []
        visited: set[int] = set()
        queue: list[tuple[tuple[str, ...], int]] = []
        if root_id is not None:
            queue.append(((), int(root_id)))

        while queue:
            parent, node_id = queue.pop(0)
            if node_id in visited:
                continue
            visited.add(node_id)

            try:
                payload = await self._async_session_request(
                    _LIST_MENUTREE, {"Id": node_id}
                )
            except OZW672Error as err:
                _LOGGER.warning("Cannot read menutree node %s: %s", node_id, err)
                continue
            if not isinstance(payload, dict):
                continue

            menus = [
                item
                for item in payload.get("MenuItems") or []
                if isinstance(item, dict)
            ]
            points = [
                item
                for item in payload.get("DatapointItems") or []
                if isinstance(item, dict)
            ]

            counters: dict[str, int] = {}

            for item in menus:
                child_id = _to_int(item.get("Id"))
                if child_id is None:
                    continue
                child_path = (*parent, _unique_title(item, counters))
                if wanted is not None and not _is_prefix(child_path, wanted):
                    continue
                queue.append((child_path, child_id))

            for item in points:
                datapoint_id = _to_int(item.get("Id"))
                if datapoint_id is None:
                    continue
                path = (*parent, _unique_title(item, counters))
                if wanted is not None and path not in wanted:
                    continue
                write_access = item.get("WriteAccess")
                results.append(
                    {
                        DP_ID: datapoint_id,
                        DP_NAME: path[-1],
                        DP_PATH: "/".join(path),
                        DP_ADDRESS: item.get("Address"),
                        DP_SUBKEY: _to_int(item.get("DpSubKey")),
                        DP_WRITE_ACCESS: str(write_access).strip().lower()
                        in _TRUE_TOKENS,
                    }
                )

        return results

    async def _async_session_request(self, path: str, params: dict[str, Any]) -> Any:
        """Perform a request, re-authenticating once if the session expired."""
        session_id = await self.async_ensure_session()
        try:
            return await self._async_request(path, {"SessionId": session_id, **params})
        except OZW672AuthError:
            _LOGGER.debug("Session expired, re-authenticating")
            await self.async_login()
            return await self._async_request(
                path, {"SessionId": self._session_id, **params}
            )

    async def async_write_datapoint(
        self,
        datapoint_id: int,
        value: Any,
        value_type: str = TYPE_NUMERIC,
    ) -> Any:
        """Write a single datapoint value."""
        session_id = await self.async_ensure_session()
        params: dict[str, Any] = {
            "SessionId": session_id,
            "Id": int(datapoint_id),
            "Type": value_type,
            "Value": value,
        }
        try:
            payload = await self._async_request(_WRITE_DATAPOINT, params)
        except OZW672AuthError:
            _LOGGER.debug("Session expired, re-authenticating")
            await self.async_login()
            params["SessionId"] = self._session_id
            payload = await self._async_request(_WRITE_DATAPOINT, params)

        error = _extract_error(payload)
        if error is not None:
            raise OZW672ApiError(f"Write of datapoint {datapoint_id} failed: {error}")
        return payload

    async def _async_login(self) -> None:
        """Perform the login handshake (lock must be held)."""
        payload = await self._async_request(
            _LOGIN, {"user": self._username, "pwd": self._password}
        )
        session_id = None
        if isinstance(payload, dict):
            for key in ("SessionId", "SessionID", "sessionId", "Sessionid"):
                if payload.get(key) is not None:
                    session_id = str(payload[key])
                    break

        if not session_id or session_id in {"0", "None", "null"}:
            raise OZW672AuthError("Login rejected by the OZW672 (check credentials)")

        self._session_id = session_id
        _LOGGER.debug("Logged in to OZW672 at %s", self.base_url)

    async def _async_request(self, path: str, params: dict[str, Any]) -> Any:
        """Perform a GET request against the OZW672 and return the JSON payload."""
        url = f"{self.base_url}{path}"
        try:
            async with asyncio.timeout(REQUEST_TIMEOUT):
                response = await self._session.get(
                    url, params=params, ssl=False if not self._verify_ssl else None
                )
                status = response.status
                text = await response.text()
        except TimeoutError as err:
            raise OZW672ConnectionError(f"Timeout while calling {path}") from err
        except aiohttp.ClientError as err:
            raise OZW672ConnectionError(f"Cannot reach {self.base_url}: {err}") from err

        if status == 401:
            raise OZW672AuthError(f"HTTP 401 on {path}")
        if status >= 400:
            raise OZW672ApiError(f"HTTP {status} on {path}")

        try:
            return json.loads(text)
        except ValueError as err:
            lowered = text.lower()
            if "session" in lowered:
                raise OZW672AuthError(f"Invalid session on {path}") from err
            raise OZW672ApiError(
                f"Non-JSON response on {path}: {text[:200]!r}"
            ) from err
