"""Constants for the Siemens OZW672 integration."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Final

DOMAIN: Final = "siemens_ozw672"
MANUFACTURER: Final = "Siemens"
MODEL: Final = "OZW672.01"

DEFAULT_PORT: Final = 80
DEFAULT_HTTPS_PORT: Final = 443
DEFAULT_SCAN_INTERVAL: Final = 60
MIN_SCAN_INTERVAL: Final = 10
MAX_SCAN_INTERVAL: Final = 3600

CONF_HOST: Final = "host"
CONF_PORT: Final = "port"
CONF_USERNAME: Final = "username"
CONF_PASSWORD: Final = "password"
CONF_USE_HTTPS: Final = "use_https"
CONF_VERIFY_SSL: Final = "verify_ssl"
CONF_SCAN_INTERVAL: Final = "scan_interval"
CONF_DEVICE_ID: Final = "device_id"
CONF_DEVICE_NAME: Final = "device_name"
CONF_GATEWAY_SERIAL: Final = "gateway_serial"
CONF_GATEWAY_FIRMWARE: Final = "gateway_firmware"
# Sequence of datapoint definitions chosen by the user (see ``Datapoint``).
CONF_DATAPOINTS: Final = "datapoints"

# Legacy option keys, kept so entry version 1 can be migrated to version 2.
CONF_CUSTOM_DATAPOINTS: Final = "custom_datapoints"
CONF_DISABLED_DATAPOINTS: Final = "disabled_datapoints"

PLATFORM_SENSOR: Final = "sensor"
PLATFORM_NUMBER: Final = "number"
PLATFORM_SELECT: Final = "select"

TYPE_NUMERIC: Final = "Numeric"
TYPE_ENUMERATION: Final = "Enumeration"
TYPE_RADIO_BUTTON: Final = "RadioButton"
TYPE_TIME_OF_DAY: Final = "TimeOfDay"

SELECTOR_VALUE_TYPE_NUMERIC: Final = "numeric"
SELECTOR_VALUE_TYPE_ENUMERATION: Final = "enumeration"
VALUE_TYPE_SELECTOR_TO_API: Final = {
    SELECTOR_VALUE_TYPE_NUMERIC: TYPE_NUMERIC,
    SELECTOR_VALUE_TYPE_ENUMERATION: TYPE_ENUMERATION,
}

SERVICE_WRITE_DATAPOINT: Final = "write_datapoint"
ATTR_DATAPOINT_ID: Final = "datapoint_id"
ATTR_VALUE: Final = "value"
ATTR_VALUE_TYPE: Final = "value_type"

# Keys of the dictionaries stored in ``CONF_DATAPOINTS``.
DP_PATH: Final = "path"
DP_ID: Final = "id"
DP_NAME: Final = "name"
DP_PLATFORM: Final = "platform"
DP_VALUE_TYPE: Final = "value_type"
DP_UNIT: Final = "unit"
DP_DEVICE_CLASS: Final = "device_class"
DP_STATE_CLASS: Final = "state_class"
DP_OPTIONS: Final = "options"
DP_MIN_VALUE: Final = "min_value"
DP_MAX_VALUE: Final = "max_value"
DP_STEP: Final = "step"
DP_WRITE_ACCESS: Final = "write_access"
DP_ADDRESS: Final = "address"
DP_SUBKEY: Final = "subkey"

# Values that mean "the controller has no value for this datapoint" (the
# datapoint exists on the bus but no sensor/module is wired to it).
INVALID_TOKENS: Final[frozenset[str]] = frozenset({"----", "---", "--", "-", "!"})

_UNIT_DEVICE_CLASS: Final[dict[str, str]] = {
    "°C": "temperature",
    "°F": "temperature",
    "K": "temperature",
    "bar": "pressure",
    "mbar": "pressure",
    "kPa": "pressure",
    "psi": "pressure",
    "kWh": "energy",
    "MWh": "energy",
    "Wh": "energy",
    "kW": "power",
    "W": "power",
    "m³": "volume",
    "m3": "volume",
    "l": "volume",
    "L": "volume",
    "m³/h": "volume_flow_rate",
    "m3/h": "volume_flow_rate",
    "l/min": "volume_flow_rate",
    "h": "duration",
    "min": "duration",
    "s": "duration",
    "Hz": "frequency",
    "V": "voltage",
    "A": "current",
}

_UNIT_STATE_CLASS: Final[dict[str, str]] = {
    "kWh": "total_increasing",
    "MWh": "total_increasing",
    "Wh": "total_increasing",
    "h": "total_increasing",
}


def guess_device_class(unit: str | None) -> str | None:
    """Return the Home Assistant device class matching a unit, if any."""
    if not unit:
        return None
    return _UNIT_DEVICE_CLASS.get(unit.strip())


def guess_state_class(unit: str | None) -> str | None:
    """Return the Home Assistant state class matching a unit, if any."""
    if not unit:
        return None
    return _UNIT_STATE_CLASS.get(unit.strip())


@dataclass(frozen=True, kw_only=True)
class Datapoint:
    """Description of a single OZW672 datapoint.

    The ``path`` (the chain of topic titles inside the controller, for example
    ``Diagnostic consommateurs/Température extérieure``) is the stable
    identity of a datapoint: the numeric identifier is generated by the
    OZW672 for the plant it is wired to and changes when the plant or the
    server parameters are refreshed.
    """

    id: int
    name: str
    path: str | None = None
    address: str | None = None
    subkey: int | None = None
    write_access: bool = False
    platform: str = PLATFORM_SENSOR
    value_type: str = TYPE_NUMERIC
    unit: str | None = None
    device_class: str | None = None
    state_class: str | None = None
    options: dict[int, str] | None = None
    min_value: float | None = None
    max_value: float | None = None
    step: float | None = None

    @property
    def key(self) -> str:
        """Return the stable key used to store and publish the value."""
        return self.path or f"id:{self.id}"
